version: '3.8
services:
db: 
 image: postgres: latest
 container_name:postgres-jwt
 environment:
    POSTGGRES_USER: postgres
    POSTGRES_PASSWORD: 123456
    POSTGRES_DB: jwr-auth-db
    TZ: Asia/Kolkata
ports:
    - "5432:5432"
volumes:
    - postgres-data:/var/lib/postgresql/data
healthcheck: 
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 10s
    timeout: 5s
    retries: 5

app:
build: 
    context: .
    dockerfile: Dockerfile
    container_name: spring-jwt-auth
    ports:
        - "8082:8082"
    depends_on:
        db:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jwr-auth-db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 123456

volumes:
    postgres-data: